### PR TITLE
Frontend download button

### PR DESCRIPTION
**Pull request by NFoithong**
Add function on download button

### CODE REVIEW

**Review by igotnowifi-official — COMMENTED** [review]
Hey Natt, why are you using jsPDF instead of filesaver? Can we postpone approval until iteration 3, team? I might be too close to iteration 2 deadline to add a new feature and test

**Comment by igotnowifi-official** [comment]
For Trevor: this is for iteration 3, please ignore for iteration 2 review

**Review by igotnowifi-official — APPROVED** [review]
lgtm, but wait for other reviews before merging?

**Comment by NFoithong** [comment]
Copy that! Will add this for iteration 3 and wait for other member approve.

**Review by poomchan-bu — APPROVED** [review]
lgtm

**Review by battalcevik — APPROVED** [review]
lgtm

**Pull request merged**
